apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
  namespace: istio-system
spec:
  secretName: tls-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "ispi.{{ .Values.domain }}"
    - "grafana.{{ .Values.domain }}"
    - "alert.{{ .Values.domain }}"
    - "prometheus.{{ .Values.domain }}"
    - "serial-gateway.{{ .Values.domain }}"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io