# apiVersion: security.istio.io/v1
# kind: RequestAuthentication
# metadata:
#   name: cafe-gateway-claims-to-headers
# spec:
#   selector:
#     matchLabels:
#       istio.io/gateway-name: cafe-gateway
#   jwtRules:
#   - issuer: "https://accounts.google.com"
#     jwksUri: "https://www.googleapis.com/oauth2/v3/certs"
#     # Forward JWT to httpbin sidecar
#     forwardOriginalToken: false
#     # outputPayloadToHeader: x-jwt-payload
#     outputClaimToHeaders:
#     - header: "x-jwt-claim-sub"
#       claim: "sub"    
#     - header: "x-jwt-claim-iss"
#       claim: "iss"    
#     - header: "x-jwt-claim-email"
#       claim: "email"    
#     - header: "x-jwt-claim-aud"
#       claim: "aud"    
#     - header: "x-jwt-claim-name"
#       claim: "name"    
#     - header: "x-jwt-claim-picture"
#       claim: "picture"    

