
releases:
- name: grafana
  namespace: kps
  chart: ../../external-charts/kube-prometheus-stack/charts/grafana
  values:
  - values/grafana.yaml.gotmpl
  
- name: kps
  namespace: kps
  chart: ../../external-charts/kube-prometheus-stack
  values:
  - values/kps.yaml.gotmpl

- name: kps-mesh
  namespace: kps
  chart: charts/kps-mesh
  values:
  - values/kps-mesh.yaml.gotmpl

commonLabels:
  app: kps