apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    # see: https://artifacthub.io/packages/helm/prometheus-community/prometheus
    chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 19.6.1
    helm:
      releaseName: prometheus
      values: |
        server:      
          ingress:
            enabled: true
            path: /
            hosts:
              - prometheus.tonygilkerson.us
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
            tls:
            - hosts:
              - prometheus.tonygilkerson.us
              secretName: prometheus-tls            
  destination:
    server: "https://kubernetes.default.svc"
    namespace: visibility
  syncPolicy:
    automated: {}