missingFileHandler: Error

helmfiles:
{{ range .Values.cafeApps }}
- path: ../../apps/{{ . }}
  values:
  - {{ $.Values | toYaml | nindent 6}}
{{ end }}

environments:
  default:
    values:
      - ../state-default-values.yaml
      - ./state-values.yaml 
