missingFileHandler: Error

helmfiles:

- path: ../../apps/kps
  values:
  - {{ $.Values | toYaml | nindent 4}}
- path: ../../apps/cafe
  values:
  - {{ $.Values | toYaml | nindent 4}}
- path: ../../apps/serial-gateway
  values:
  - {{ $.Values | toYaml | nindent 4}}
- path: ../../apps/castopod
  values:
  - {{ $.Values | toYaml | nindent 4}}
- path: ../../apps/ispy
  values:
  - {{ $.Values | toYaml | nindent 4}}



environments:
  default:
    values:
      - clusterName: weeble
      


  
