apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weeble
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: env/weeble/k8s
    repoURL: 'https://github.com/tonygilkerson/cafe.git'
    targetRevision: HEAD
  sources: []
  project: default
