#
#  grafana
#
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
spec:
  parentRefs:
  - name: cafe-gateway
    namespace: istio-system
    sectionName: https
  hostnames:
  - "grafana.{{ .Values.domain }}"    
  rules:
  - backendRefs:
    - name: grafana
      weight: 1
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-http-redirect
spec:
  parentRefs:
  - name: cafe-gateway
    namespace: istio-system
    sectionName: http
  hostnames:
  - "grafana.{{ .Values.domain }}"       
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
---
#
#  alert
#
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: alert
spec:
  parentRefs:
  - name: cafe-gateway
    namespace: istio-system
    sectionName: https
  hostnames:
  - "alert.{{ .Values.domain }}"    
  rules:
  - backendRefs:
    - name: kps-kube-prometheus-stack-alertmanager
      weight: 1
      port: 9093
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: alert-http-redirect
spec:
  parentRefs:
  - name: cafe-gateway
    namespace: istio-system
    sectionName: http
  hostnames:
  - "alert.{{ .Values.domain }}"       
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
---
#
#  prometheus
#
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus
spec:
  parentRefs:
  - name: cafe-gateway
    namespace: istio-system
    sectionName: https
  hostnames:
  - "prometheus.{{ .Values.domain }}"    
  rules:
  - backendRefs:
    - name: kps-kube-prometheus-stack-prometheus
      weight: 1
      port: 9090
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus-http-redirect
spec:
  parentRefs:
  - name: cafe-gateway
    namespace: istio-system
    sectionName: http
  hostnames:
  - "prometheus.{{ .Values.domain }}"       
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
---
