apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
spec:
  gateways:
  - istio-system/istio-ingress-gateway
  hosts:
  - grafana.{{ .Values.domain }}
  http:
  - name: grafana
    route:
    - destination:
        port:
          number: 80
        host: grafana
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: alert
spec:
  gateways:
  - istio-system/istio-ingress-gateway
  hosts:
  - alert.{{ .Values.domain }}
  http:
  - name: alert
    route:
    - destination:
        port:
          number: 9093
        host: kps-kube-prometheus-stack-alertmanager
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus
spec:
  gateways:
  - istio-system/istio-ingress-gateway
  hosts:
  - prometheus.{{ .Values.domain }}
  http:
  - name: prometheus
    route:
    - destination:
        port:
          number: 9090
        host: kps-kube-prometheus-stack-prometheus

