apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitlabdocker
  name: gitlabdocker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlabdocker
  strategy: {}
  template:
    metadata:
      labels:
        app: gitlabdocker
    spec:
      containers:
      - image: {{ .Values.image.repository }}
        name: gitlab
        hostname: {{ .Values.hostname }}
        env:
        - name: GITLAB_OMNIBUS_CONFIG
          value: "external_url 'http://{{ .Values.hostname }}'"
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        - name: ssh
          containerPort: 22
          protocol: TCP
        resources:
          requests:
            memory: 1G
            cpu: 500m
          limits:
            memory: 2G
            cpu: 2000m
        volumeMounts:
        - mountPath: "/srv/gitlab"
          name: gitlabhome
      volumes:
        - name: gitlabhome
          persistentVolumeClaim:
            claimName: gitlabhome
status: {}
