apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlabhome
spec:
  storageClassName: microk8s-hostpath
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi