apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: mbx-door-open
  namespace: cafe
  labels:
    tonygilkerson.us/alerting: enabled
spec:
  route:
    groupBy: ['job']
    groupWait: 3s
    groupInterval: 15m
    repeatInterval: 12h
    receiver: webhook
    matchers:
    - matchType: =
      name: alertname
      value: MbxDoorOpen        
  receivers:
  - name: webhook
    webhookConfigs:
    - urlSecret: 
        key: url
        name: slack-webhook-url-mbx-door
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: mbx-heartbeat
  namespace: cafe
  labels:
    tonygilkerson.us/alerting: enabled
spec:
  route:
    groupBy: ['job']
    groupWait: 3s
    groupInterval: 15m
    repeatInterval: 12h
    receiver: webhook
    matchers:
    - matchType: =
      name: alertname
      value: MbxHeartbeat        
  receivers:
  - name: webhook
    webhookConfigs:
    - urlSecret: 
        key: url
        name: slack-webhook-url-mbx-heartbeat
