apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: mbx-door-open
  namespace: cafe
  labels:
    tonygilkerson.us/alerting: enabled
spec:
  route:
    groupBy: ['job']
    groupWait: 1m
    groupInterval: 15m
    repeatInterval: 12h
    receiver: slack-notifications-mbx-door
    matchers:
    - matchType: =
      name: alertname
      value: MbxDoorOpen        
  receivers:
  - name: slack-notifications-mbx-door
    slackConfigs:
    - channel: '#mbx-door'
      apiURL:
        name: slack-webhook-url-mbx-door
        key: url
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: mbx-heartbeat
  namespace: cafe
  labels:
    tonygilkerson.us/alerting: enabled
spec:
  route:
    groupBy: ['job']
    groupWait: 3s
    groupInterval: 1m
    repeatInterval: 12h
    # groupWait: 3s
    # groupInterval: 15m
    # repeatInterval: 12h
    # receiver: webhook-mbx-heartbeat
    receiver: slack-notifications
    matchers:
    - matchType: =
      name: alertname
      value: MbxHeartbeat        
  receivers:
  - name: slack-notifications
    slackConfigs:
    - channel: '#mbx-notifications'
      apiURL:
        name: slack-webhook-url-mbx-notifications
        key: url        



