apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: mbx-door-open
  namespace: cafe
  labels:
    tonygilkerson.us/alerting: enabled
spec:
  route:
    groupBy: ['job']
    groupWait: 3s
    groupInterval: 15m
    repeatInterval: 12h
    receiver: webhook
    matchers:
    - matchType: =
      name: alertname
      value: MbxDoorOpen        
  receivers:
  - name: webhook
    webhookConfigs:
    - urlSecret: 
        key: url
        name: slack-webhook-url-mbx-door
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: mbx-heartbeat
  namespace: cafe
  labels:
    tonygilkerson.us/alerting: enabled
spec:
  route:
    groupBy: ['job']
    groupWait: 3s
    groupInterval: 1m
    repeatInterval: 1m
    # groupWait: 3s
    # groupInterval: 15m
    # repeatInterval: 12h
    # receiver: webhook-mbx-heartbeat
    receiver: slack-notifications
    matchers:
    - matchType: =
      name: alertname
      value: MbxHeartbeat        
  receivers:
  # - name: webhook-mbx-heartbeat
  #   webhookConfigs:
  #   - urlSecret: 
  #       key: url
  #       name: slack-webhook-url-mbx-heartbeat
  - name: slack-notifications
    slackConfigs:
    - channel: '#mbx-notifications'
      apiURL:
        name: slack-webhook-url-mbx-notifications
        key: url        
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: watchdog-test
  namespace: cafe
  labels:
    tonygilkerson.us/alerting: enabled
spec:
  route:
    groupBy: ['job']
    groupWait: 1m
    groupInterval: 1m
    repeatInterval: 1m
    receiver: slack-notifications
  receivers:
  - name: slack-notifications
    slackConfigs:
    - channel: '#mbx-notifications'
      apiURL:
        name: slack-webhook-url-mbx-notifications
        key: url
      # httpConfig:
      #   bearerTokenSecret:
      #     name: slack-webhook-url-mbx-notifications
      #     key: url


