apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: mbx-door-open
  namespace: cafe
  labels:
    tonygilkerson.us/alerting: enabled
spec:
  route:
    groupBy: ['job']
    groupWait: 3s
    groupInterval: 5s
    repeatInterval: 12h
    receiver: slack-notifications-mbx-door
    matchers:
    - matchType: =
      name: alertname
      value: MbxDoorOpen        
  receivers:
  - name: slack-notifications-mbx-door
    slackConfigs:
    - channel: '#mbx-door'
      apiURL:
        name: slack-webhook-url-mbx-door
        key: url
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: mbx-cars
  namespace: cafe
  labels:
    tonygilkerson.us/alerting: enabled
spec:
  route:
    groupBy: ['job']
    groupWait: 3s
    groupInterval: 5s
    repeatInterval: 12h
    receiver: slack-notifications-mbx-cars
    matchers:
    - matchType: =
      name: alertname
      value: MbxCars        
  receivers:
  - name: slack-notifications-mbx-cars
    slackConfigs:
    - channel: '#mbx-cars'
      apiURL:
        name: slack-webhook-url-mbx-cars
        key: url
 



