apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: argocd
spec:
  limits:
  - default: # this section defines default limits
      cpu: 500m
      memory: 128Mi
    defaultRequest: # this section defines default requests
      cpu: 250m
      memory: 64Mi
    max: # max and min define the limit range
      cpu: 1
      memory: 1Gi
    min:
      cpu: 500m
      memory: 512Mi
    type: Container