apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: castopod-media
spec:
  storageClassName: microk8s-hostpath
  accessModes: 
  - ReadWriteOnce
  resources:
   requests:
    storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: castopod-db
spec:
  storageClassName: microk8s-hostpath
  accessModes: 
  - ReadWriteOnce
  resources:
   requests:
    storage: 3Gi