apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: castopod
  annotations:
    # Create a random secret for castopod to use and shere with the db
    # This secret is create during the install, after that you are on your own
    "helm.sh/hook": post-install
stringData:
  cpDb: castopod
  cpUser: castopod
  cpPassword: {{ randAlphaNum 32 }}
