apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: castopod
  name: castopod
spec:
  ports:
  - name: ui
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: castopod
  type: ClusterIP

