apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: serial-gateway
  labels:
    # release: kps
    tonygilkerson.us/alerting: enabled
spec:
  selector:
    matchLabels:
      app: serial-gateway
  endpoints:
  - port: http
