# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: cafe
#   namespace: cafe
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: tonygilkerson.us
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: cafe
#             port:
#               number: 80
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cafe
  annotations:
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: letsencrypt-cluster-prod  
spec:
  rules:
  - host: {{ .Values.domain | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cafe
            port:
              number: 80
  tls:
  - hosts:
    - {{ .Values.domain | quote }}
    secretName: cafe-tls