apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: cafe
spec:
  limits:
  - default: # this section defines default limits
      cpu: 32m
      memory: 64Mi
    defaultRequest: # this section defines default requests
      cpu: 32m
      memory: 32Mi
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: iot
spec:
  limits:
  - default: # this section defines default limits
      cpu: 32m
      memory: 64Mi
    defaultRequest: # this section defines default requests
      cpu: 32m
      memory: 32Mi
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: kps
spec:
  limits:
  - default: # this section defines default limits
      cpu: 64m
      memory: 256Mi
    defaultRequest: # this section defines default requests
      cpu: 32m
      memory: 32Mi
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: cert-manager
spec:
  limits:
  - default: # this section defines default limits
      cpu: 32m
      memory: 64Mi
    defaultRequest: # this section defines default requests
      cpu: 32m
      memory: 32Mi
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: ingress
spec:
  limits:
  - default: # this section defines default limits
      cpu: 64m
      memory: 128Mi
    defaultRequest: # this section defines default requests
      cpu: 32m
      memory: 32Mi
    type: Container


