# 
# The cafe namespace is created when this chart is deployed
# So we don't need to do it here
#
# apiVersion: v1
# kind: Namespace
# metadata:
#   name:  cafe
#   labels:
#     tonygilkerson.us/alerting: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name:  serial-gateway
  labels:
    {{- include "ns-common.labels" . | nindent 4 }}
    {{- include "ns-pod-security-privileged.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name:  cert-manager
  labels:
    {{- include "ns-common.labels" . | nindent 4 }}
    {{- include "ns-pod-security-restricted.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name:  ispy
  labels:
    {{- include "ns-common.labels" . | nindent 4 }}
    {{- include "ns-pod-security-restricted.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name:  kps
  labels:
    {{- include "ns-common.labels" . | nindent 4 }}
    {{- include "ns-pod-security-baseline.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name:  castopod
  labels:
    {{- include "ns-common.labels" . | nindent 4 }}
    {{- include "ns-pod-security-restricted.labels" . | nindent 4 }}
---
# I would like to run this as restricted but I had issue running caddy as non root
# I need to look into that
apiVersion: v1
kind: Namespace
metadata:
  name:  notebook
  labels:
    {{- include "ns-common.labels" . | nindent 4 }}
    {{- include "ns-pod-security-baseline.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name:  httpbin
  labels:
    {{- include "ns-common.labels" . | nindent 4 }}
    {{- include "ns-pod-security-baseline.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name:  rabbitmq-system
  labels:
    {{- include "ns-common.labels" . | nindent 4 }}
    {{- include "ns-pod-security-baseline.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name:  rabbitmq
  labels:
    {{- include "ns-common.labels" . | nindent 4 }}
    {{- include "ns-pod-security-baseline.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name:  keda
  labels:
    {{- include "ns-common.labels" . | nindent 4 }}
    {{- include "ns-pod-security-baseline.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name:  gitlab
  labels:
    {{- include "ns-common.labels" . | nindent 4 }}
    {{- include "ns-pod-security-baseline.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name:  gitlab-runner
  labels:
    {{- include "ns-common.labels" . | nindent 4 }}
    {{- include "ns-pod-security-privileged.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name:  home-assistant
  labels:
    {{- include "ns-common.labels" . | nindent 4 }}
    {{- include "ns-pod-security-privileged.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name:  dagger
  labels:
    {{- include "ns-common.labels" . | nindent 4 }}
    {{- include "ns-pod-security-privileged.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name:  open-webui
  labels:
    {{- include "ns-common.labels" . | nindent 4 }}
    {{- include "ns-pod-security-baseline.labels" . | nindent 4 }}
