apiVersion: v1
kind: Service
metadata:
  labels:
    app: cafe
  name: cafe
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: cafe
  type: ClusterIP

