missingFileHandler: Error

releases:

- name: istio-base
  namespace: istio-system
  chart: ../../external-charts/base
  wait: true

- name: istiod
  namespace: istio-system
  chart: ../../external-charts/istiod
  wait: true
  values:
  - values/istiod.yaml.gotmpl

# I think this is the istio way not the GatewayAPI way
# remove this if not needed with GatewayAPI
#
# - name: istio-ingress-gateway
#   namespace: istio-system
#   chart: ../../external-charts/gateway
#   values:
#   - values/istio-ingress-gateway.yaml.gotmpl
#   needs:
#   - istio-system/istiod

- name: istio-etc
  namespace: istio-system
  chart: charts/istio-etc
  values:
  - values/istio-etc.yaml.gotmpl

commonLabels:
  app: service-mesh