# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: cafe
#   namespace: cafe
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: tonygilkerson.us
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: cafe
#             port:
#               number: 80
#   # tls:
#   # - hosts:
#   #   - tonygilkerson.us             
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cafe
            port:
              number: 80