apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ispy
  name: ispy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ispy
  strategy: {}
  template:
    metadata:
      labels:
        app: ispy
    spec:
      serviceAccountName: ispy
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000    
      containers:   
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          name: ispy
          env:
          - name: ISPY_IN_CLUSTER
            value: "true"
          - name: ISPY_SERVER_PORT
            value: "8080"
          # - name: ISPY_WWW_ROOT
          #   value: Let this default to the folder where the bin is running
          resources:
            requests:
              cpu: 32m
              memory: 32Mi
            limits:
              cpu: 500m
              memory: 64Mi
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP              
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault

