apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  name: ispy
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
  - host: ispy.{{ .Values.domain }}
    http:
      paths:
      - backend:
          service:
            name: ispy
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - ispy.{{ .Values.domain }}
    secretName: ispy-tls

