apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: home-assistant
  name: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  strategy: {}
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
      - image: ghcr.io/home-assistant/home-assistant:stable
        name: home-assistant
        volumeMounts:
        - name: dbus
          mountPath: /run/dbus
        - name: localtime
          mountPath: /etc/localtime
        - name: config
          mountPath: /config
        - name: host-devices
          mountPath: /dev
        securityContext:
          privileged: true
      volumes:
      - name: dbus
        persistentVolumeClaim:
          claimName: ha-dbus
      - name: localtime
        persistentVolumeClaim:
          claimName: ha-localtime
      - name: config
        persistentVolumeClaim:
          claimName: ha-config
      - name: host-devices
        hostPath:
          path: /dev

