apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: home-assistant
spec:
  hostnames:
  - hadev.tonygilkerson.us
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: cafe-gateway
    namespace: istio-system
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: home-assistant
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /