apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha-localtime
spec:
  storageClassName: "microk8s-hostpath"
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha-dbus
spec:
  storageClassName: "microk8s-hostpath"
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha-config
spec:
  storageClassName: "microk8s-hostpath"
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi