apiVersion: v1
kind: Service
metadata:
  labels:
    app: home-assistant
  name: home-assistant
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8123
  selector:
    app: home-assistant

