apiVersion: v1
kind: Service
metadata:
  labels:
    app: ollama
  name: ollama
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 11434
    nodePort: 30434
  selector:
    app: ollama
  type: NodePort

