apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      # securityContext:
      #   fsGroup: 65532
      containers:
      - name: httpbin
        image: docker.io/kong/httpbin
        ports:
        - containerPort: 80
        # securityContext:
        #   allowPrivilegeEscalation: false
        #   capabilities:
        #     drop:
        #     - ALL
        #   readOnlyRootFilesystem: true        