apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httpbin-https
spec:
  parentRefs:
  - name: cafe-gateway
    namespace: istio-system
    sectionName: http
  rules:
  - backendRefs:
    - name: httpbin
      port: 80
    # filters:
    # - type: RequestHeaderModifier
    #   requestHeaderModifier:
    #     add:
    #     - name: I_AM
    #       value: app1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httpbin
spec:
  hostnames:
  - httpbin.tonygilkerson.us
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: cafe-gateway
    namespace: istio-system
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: httpbin
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /