apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-file-transfer
  name: simple-file-transfer
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30123
  selector:
    app: simple-file-transfer
  type: LoadBalancer
