apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: notebook
spec:
  parentRefs:
  - name: cafe-gateway
    namespace: istio-system
    sectionName: https-notebook
  # hostnames:
  # - "notebook.{{ .Values.domain }}"    
  rules:
  - backendRefs:
    - name: notebook
      weight: 1
      port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: notebook-http-redirect
spec:
  parentRefs:
  - name: cafe-gateway
    namespace: istio-system
    sectionName: http-notebook
  # hostnames:
  # - "notebook.{{ .Values.domain }}"       
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
