apiVersion: v1
kind: Service
metadata:
  labels:
    app: notebook
  name: notebook
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: notebook
  type: ClusterIP

