{
 "title": "Marty",
 "tags": [ "iot" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Heartbeats",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(mbx_road_main_loop_heartbeat_count[15m])))",
     "legendFormat": "Road"
    }
   ]
  },
  {
   "title": "Charger Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mbx_charger_charge_status", "legendFormat": "Charger" },
    { "expr": "mbx_charger_power_status", "legendFormat": "Power" }
   ]
  },
  {
   "title": "TLDR ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(mbx_mule_alarm_count[$__range])))",
     "legendFormat": "Mule"
    },
    {
     "expr": "round(sum(increase(mbx_mailbox_door_opened_count[$__range])))",
     "legendFormat": "Door"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "increase(mbx_mule_alarm_count[5m])",
     "legendFormat": "Arrived"
    }
   ]
  },
  {
   "title": "Heartbeat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "mbx_road_main_loop_heartbeat_count",
     "legendFormat": "Heartbeat"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "expr": "mbx_temperature_fahrenheit", "legendFormat": "Temperature" }
   ]
  },
  {
   "title": "Charger",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    { "expr": "mbx_charger_charge_status", "legendFormat": "Charger" }
   ]
  },
  {
   "title": "Absolute Counts",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mbx_mule_alarm_count", "legendFormat": "Mule" },
    { "expr": "mbx_mailbox_door_opened_count", "legendFormat": "Door" },
    { "expr": "mbx_heard_sound_count", "legendFormat": "Heard" }
   ]
  }
 ]
}