apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: publisher
  name: publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  strategy: {}
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - |
          while true; do
            #
            # publish messages
            #
            for i in $(seq 1 500); do
              echo "publish demo message $i"
              rabbitmqadmin publish exchange=demo.fanout routing_key=demoq payload="demo" -u $USERNAME -p $PASSWORD --host $HOST --port 15672

            done
            rabbitmqadmin list queues -u $USERNAME -p $PASSWORD --host $HOST --port 15672
            sleep 300
          done

        image: rabbitmq:4-management
        name: publisher
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: zoomq-default-user
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: zoomq-default-user
              key: password
        - name: HOST
          valueFrom:
            secretKeyRef:
              name: zoomq-default-user
              key: host
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: consumer
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  strategy: {}
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - |
          while true; do
            #
            # consume message
            #
            for i in $(seq 1 3); do
              rabbitmqadmin get queue=demoq ackmode=ack_requeue_false -u $USERNAME -p $PASSWORD --host $HOST --port 15672
            done
            sleep 1
          done

        image: rabbitmq:4-management
        name: consumer
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: zoomq-default-user
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: zoomq-default-user
              key: password
        - name: HOST
          valueFrom:
            secretKeyRef:
              name: zoomq-default-user
              key: host
