apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-scaledobject
spec:
  scaleTargetRef:
    name: consumer
  triggers:
  - type: rabbitmq
    metadata:
      protocol: amqp
      queueName: demoq
      mode: QueueLength
      # Example: if one pod can handle 10 messages, set value to 10. 
      # If the actual number of messages in the queue is 30, the scaler scales to 3 pods.
      value: "200" # message backlog target per replica (ie each pod can consume 1 message per second)
      activationValue: "200" 
    authenticationRef:
      name: keda-trigger-auth-rabbitmq-conn