name: Cafe CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
# on:
#   push:
#     tags:
#     - 'v*'

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      with:
        semantic_version: 19.0.5  # It is recommended to specify a version range
                                  # for semantic-release when using
                                  # semantic-release-action lower than @v3
      env:
        GITHUB_TOKEN: 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

  # build:
  #   needs: semantic-release
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Login to GitHub Container Registry
  #     uses: docker/login-action@v1
  #     with:
  #       registry: ghcr.io
  #       username: ${{ github.repository_owner }}
  #       password: ${{ secrets.AEG_REGISTRY_TOKEN }}

  #   - name: Build and Push Docker Image
  #     uses: docker/build-push-action@v2
  #     with:
  #       push: true # Will only build if this is not here
  #       tags: |
  #         ghcr.io/${{ github.repository }}:latest