name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        export DOCKER_BUILDKIT=0
        docker build --progress=plain --platform="linux/amd64" . --file Dockerfile --tag cafe:$(date +%s)
