name: Semantic Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      id: semantic 
      with:
        dry_run: false
        semantic_version: 19.0.5  # It is recommended to specify a version range
                                  # for semantic-release when using
                                  # semantic-release-action lower than @v3
      env:
        GITHUB_TOKEN: ${{ secrets.AEG_CAFE_ADMIN }}
        GH_TOKEN: ${{ secrets.AEG_CAFE_ADMIN }}

    - name: Semantic Release Version
      if: steps.semantic.outputs.new_release_published == 'true'
      run: |
        echo Semantic Release Version ${{ steps.semantic.outputs.new_release_version }}

    - name: Login to Container Registry
      if: steps.semantic.outputs.new_release_published == 'true'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.AEG_REGISTRY_TOKEN }}

    - name: Build and Push Container Image
      if: steps.semantic.outputs.new_release_published == 'true'
      uses: docker/build-push-action@v2
      with:
        push: true # Will only build if this is not here
        tags: |
          ghcr.io/${{ github.repository }}:${{ steps.semantic.outputs.new_release_version }}